export type ServiceStatus = "active" | "coming_soon" | "disabled";

export interface TransportService {
  id: string;
  title: string;
  titleTm: string;
  icon: string;
  color: string;
  status: ServiceStatus;
  href?: string;
  description: string;
}

export interface TransportCategory {
  id: string;
  title: string;
  titleTm: string;
  icon: string;
  color: string;
  gradient: string;
  enabled: boolean;
  services: TransportService[];
}

export const TRANSPORT_CATEGORIES: TransportCategory[] = [
  {
    id: "dowlet-ulaglary",
    title: "Döwlet ulaglary",
    titleTm: "Döwlet ulaglary",
    icon: "fas fa-landmark",
    color: "#0d9488",
    gradient: "linear-gradient(135deg, #0d9488, #14b8a6)",
    enabled: true,
    services: [
      {
        id: "howayollary",
        title: "Howaýollary",
        titleTm: "Aviabiletlar",
        icon: "fas fa-plane",
        color: "#0ea5e9",
        status: "coming_soon",
        description: "Içerki & Halkara uçuşlar",
      },
      {
        id: "demiryollary",
        title: "Demirýollary",
        titleTm: "Poyezd biletleri",
        icon: "fas fa-train",
        color: "#0d9488",
        status: "active",
        href: "/demiryol",
        description: "Kart tölegsiz bilet satyn alyň",
      },
      {
        id: "saherara-awtobus",
        title: "Şäherara awtobuslar",
        titleTm: "Viloyatara",
        icon: "fas fa-bus",
        color: "#7c3aed",
        status: "coming_soon",
        description: "Welaýatlar arasy awtobus",
      },
      {
        id: "saher-awtobus",
        title: "Şäher içi awtobuslar",
        titleTm: "Ýol kart tölegleri",
        icon: "fas fa-bus-alt",
        color: "#059669",
        status: "coming_soon",
        description: "Ýol kart tölegleri",
      },
    ],
  },
  {
    id: "hususy-gatnawlar",
    title: "Hususy we Welaýatara",
    titleTm: "Hususy we Welaýatara gatnawlar",
    icon: "fas fa-car",
    color: "#f59e0b",
    gradient: "linear-gradient(135deg, #f59e0b, #f97316)",
    enabled: true,
    services: [
      {
        id: "welayatara-taksi",
        title: "Welaýatara taksiler",
        titleTm: "Pyatak / BlaBlaCar",
        icon: "fas fa-car-side",
        color: "#f59e0b",
        status: "coming_soon",
        description: "Welaýatara taksiler",
      },
      {
        id: "saher-taksi",
        title: "Şäher içi taksi",
        titleTm: "Şäher içi taksi",
        icon: "fas fa-taxi",
        color: "#f97316",
        status: "coming_soon",
        description: "Çalt we arzan şäher taksisi",
      },
      {
        id: "arenda-masyn",
        title: "Arenda maşynlar",
        titleTm: "Arenda maşynlar",
        icon: "fas fa-key",
        color: "#8b5cf6",
        status: "coming_soon",
        description: "Günlük we aýlyk kärendä",
      },
      {
        id: "ewakuator",
        title: "Ewakuator hyzmatlary",
        titleTm: "Ewakuator hyzmatlary",
        icon: "fas fa-truck-pickup",
        color: "#ef4444",
        status: "coming_soon",
        description: "Bejeriş ýerine eltmek",
      },
    ],
  },
  {
    id: "logistika",
    title: "Logistika we Ýük daşama",
    titleTm: "Logistika we Ýük daşama",
    icon: "fas fa-boxes",
    color: "#6366f1",
    gradient: "linear-gradient(135deg, #6366f1, #8b5cf6)",
    enabled: true,
    services: [
      {
        id: "yuk-taksi",
        title: "Ýük taksisi",
        titleTm: "Şäher içinde",
        icon: "fas fa-truck",
        color: "#6366f1",
        status: "coming_soon",
        description: "Şäher içindäki ýük daşama",
      },
      {
        id: "welayatara-yukdas",
        title: "Welaýatara ýükdaşama",
        titleTm: "Kamaz / Fura",
        icon: "fas fa-truck-moving",
        color: "#8b5cf6",
        status: "coming_soon",
        description: "Kamaz / Fura daşama",
      },
      {
        id: "kuryer",
        title: "Tiz poçta / Kuryer",
        titleTm: "Kuryer hyzmaty",
        icon: "fas fa-shipping-fast",
        color: "#ec4899",
        status: "coming_soon",
        description: "Çalt eltip bermek hyzmaty",
      },
    ],
  },
  {
    id: "dynch-syyyahat",
    title: "Dynç alyş we Syýahat",
    titleTm: "Dynç alyş we Syýahat",
    icon: "fas fa-umbrella-beach",
    color: "#06b6d4",
    gradient: "linear-gradient(135deg, #06b6d4, #0ea5e9)",
    enabled: true,
    services: [
      {
        id: "awaza",
        title: "Awaza gatnawlary",
        titleTm: "Awaza gatnawlary",
        icon: "fas fa-water",
        color: "#06b6d4",
        status: "coming_soon",
        description: "Awaza milli syýahatçylyk zolagy",
      },
      {
        id: "sanatoriya",
        title: "Sanatoriýa transporty",
        titleTm: "Archman, Ýyly Suw",
        icon: "fas fa-hot-tub",
        color: "#0ea5e9",
        status: "coming_soon",
        description: "Archman, Ýyly Suw sanatoriýalary",
      },
      {
        id: "ekskursia",
        title: "Syýahatçylyk ugurlary",
        titleTm: "Ekskursiyalar",
        icon: "fas fa-map-marked-alt",
        color: "#10b981",
        status: "coming_soon",
        description: "Taryhy ýerler boýunça syýahatlar",
      },
    ],
  },
  {
    id: "pyygg-sanly",
    title: "PÝGG we Sanly hyzmatlar",
    titleTm: "PÝGG we Sanly hyzmatlar",
    icon: "fas fa-shield-alt",
    color: "#dc2626",
    gradient: "linear-gradient(135deg, #dc2626, #ef4444)",
    enabled: true,
    services: [
      {
        id: "jerimeler",
        title: "PÝGG jerimeler",
        titleTm: "Jarimalar",
        icon: "fas fa-exclamation-circle",
        color: "#dc2626",
        status: "coming_soon",
        description: "PÝGG jerimelerini tölemek",
      },
      {
        id: "tehosmotr",
        title: "Tehnik gözegçilik",
        titleTm: "Tehosmotr",
        icon: "fas fa-tools",
        color: "#d97706",
        status: "coming_soon",
        description: "Ulag tehniki barlagy",
      },
      {
        id: "sugurta",
        title: "Ulag ätiýaçlandyryş",
        titleTm: "Sug'urta",
        icon: "fas fa-file-contract",
        color: "#7c3aed",
        status: "coming_soon",
        description: "Ulag ätiýaçlandyryşy",
      },
    ],
  },
  {
    id: "yol-komegi",
    title: "Ýol kömegi",
    titleTm: "Ýol kömegi",
    icon: "fas fa-life-ring",
    color: "#ea580c",
    gradient: "linear-gradient(135deg, #ea580c, #f97316)",
    enabled: true,
    services: [
      {
        id: "yangyc",
        title: "Ýangyç eltmek",
        titleTm: "Yoqilg'i eltmek",
        icon: "fas fa-gas-pump",
        color: "#ea580c",
        status: "coming_soon",
        description: "Ýol başynda ýangyç kömegi",
      },
      {
        id: "shinamontaj",
        title: "Göçme şinamontaž",
        titleTm: "Şinamontaž",
        icon: "fas fa-circle-notch",
        color: "#f59e0b",
        status: "coming_soon",
        description: "Tekerini çalyşmak kömegi",
      },
      {
        id: "akkumulator",
        title: "Akkumulyator otlandyrmak",
        titleTm: "Prikurka",
        icon: "fas fa-car-battery",
        color: "#16a34a",
        status: "coming_soon",
        description: "Batareýa otlandyrma kömegi",
      },
    ],
  },
  {
    id: "yorite-gatnawlar",
    title: "Ýörite gatnawlar",
    titleTm: "Ýörite gatnawlar",
    icon: "fas fa-star",
    color: "#db2777",
    gradient: "linear-gradient(135deg, #db2777, #ec4899)",
    enabled: true,
    services: [
      {
        id: "zenanlar",
        title: "Zenanlar üçin",
        titleTm: "Faqat ayollar uchun",
        icon: "fas fa-female",
        color: "#db2777",
        status: "coming_soon",
        description: "Diňe zenanlar üçin taksi",
      },
      {
        id: "mekdep-awtobus",
        title: "Mekdep awtobusy",
        titleTm: "Mekdep awtobusy",
        icon: "fas fa-school",
        color: "#f59e0b",
        status: "coming_soon",
        description: "Mekdep okuwçylary üçin",
      },
    ],
  },
  {
    id: "mikromobillik",
    title: "Mikromobillik",
    titleTm: "Mikromobillik",
    icon: "fas fa-bolt",
    color: "#16a34a",
    gradient: "linear-gradient(135deg, #16a34a, #22c55e)",
    enabled: true,
    services: [
      {
        id: "samokat",
        title: "Tokly samokatlar",
        titleTm: "Elektrikli samokatlar",
        icon: "fas fa-skating",
        color: "#16a34a",
        status: "coming_soon",
        description: "Elektrikli samokatlary kärendä",
      },
      {
        id: "welosiped",
        title: "Welosiped kärendesi",
        titleTm: "Welosiped kärendesi",
        icon: "fas fa-bicycle",
        color: "#22c55e",
        status: "coming_soon",
        description: "Elektrikli welosiped kärendesi",
      },
    ],
  },
  {
    id: "bilim-tayyarlyk",
    title: "Bilim we Sanly taýýarlyk",
    titleTm: "Bilim we Sanly taýýarlyk",
    icon: "fas fa-graduation-cap",
    color: "#7c3aed",
    gradient: "linear-gradient(135deg, #7c3aed, #8b5cf6)",
    enabled: true,
    services: [
      {
        id: "awto-mekdep",
        title: "Awto-mekdepler",
        titleTm: "Haydovchilik maktablari",
        icon: "fas fa-steering-wheel",
        color: "#7c3aed",
        status: "coming_soon",
        description: "Sürüjilik mekdepleri",
      },
      {
        id: "pyygg-synag",
        title: "PÝGG synaglary",
        titleTm: "Testlar",
        icon: "fas fa-clipboard-check",
        color: "#6366f1",
        status: "coming_soon",
        description: "Onlaýn sürüjilik synaglary",
      },
    ],
  },
  {
    id: "ulag-bazary",
    title: "Ulag bazary",
    titleTm: "Ulag bazary",
    icon: "fas fa-store",
    color: "#0891b2",
    gradient: "linear-gradient(135deg, #0891b2, #06b6d4)",
    enabled: true,
    services: [
      {
        id: "ulag-bildirish",
        title: "Ulag bildirişleri",
        titleTm: "Avtobozor e'lonlari",
        icon: "fas fa-car",
        color: "#0891b2",
        status: "coming_soon",
        description: "Ulag aluw we satuw",
      },
      {
        id: "plaka-bazary",
        title: "Plaka bazary",
        titleTm: "Raqamlar bazari",
        icon: "fas fa-parking",
        color: "#06b6d4",
        status: "coming_soon",
        description: "Awtoulag belgilerini söwda et",
      },
    ],
  },
];
