export type ServiceStatus = "active" | "coming_soon" | "disabled";

export interface PaymentService {
  id: string;
  title: string;
  subtitle: string;
  icon: string;
  iconFamily: "Ionicons" | "MaterialCommunityIcons" | "Feather";
  color: string;
  status: ServiceStatus;
  route?: string;
}

export interface PaymentCategory {
  id: string;
  title: string;
  icon: string;
  iconFamily: "Ionicons" | "MaterialCommunityIcons" | "Feather";
  color: string;
  gradientStart: string;
  gradientEnd: string;
  enabled: boolean;
  services: PaymentService[];
}

export const PAYMENT_CATEGORIES: PaymentCategory[] = [
  {
    id: "ulgamlar",
    title: "Ulgamlar we Sanly hyzmatlary",
    icon: "apps-outline",
    iconFamily: "Ionicons",
    color: "#f59e0b",
    gradientStart: "#d97706",
    gradientEnd: "#f59e0b",
    enabled: true,
    services: [
      {
        id: "aydym-com",
        title: "Aydym.com",
        subtitle: "Premium abonement",
        icon: "musical-notes-outline",
        iconFamily: "Ionicons",
        color: "#7c3aed",
        status: "active",
        route: "/ulgamlar",
      },
      {
        id: "hinlen",
        title: "Hiňlen",
        subtitle: "Premium abonement",
        icon: "headset-outline",
        iconFamily: "Ionicons",
        color: "#db2777",
        status: "active",
        route: "/ulgamlar",
      },
      {
        id: "belet-film",
        title: "Belet film",
        subtitle: "Hasaby doldurmak",
        icon: "film-outline",
        iconFamily: "Ionicons",
        color: "#dc2626",
        status: "active",
        route: "/ulgamlar",
      },
      {
        id: "belet-music",
        title: "Belet music",
        subtitle: "Hasaby doldurmak",
        icon: "musical-note-outline",
        iconFamily: "Ionicons",
        color: "#0ea5e9",
        status: "active",
        route: "/ulgamlar",
      },
    ],
  },
  {
    id: "hojalyk-jemagat",
    title: "Hojalyk we Jemagat hyzmatlary",
    icon: "home-outline",
    iconFamily: "Ionicons",
    color: "#0ea5e9",
    gradientStart: "#0369a1",
    gradientEnd: "#0ea5e9",
    enabled: true,
    services: [
      {
        id: "agyz-suw",
        title: "Agyz suw tölegi",
        subtitle: "Suw tölegi",
        icon: "water-outline",
        iconFamily: "Ionicons",
        color: "#0ea5e9",
        status: "coming_soon",
      },
      {
        id: "tebigi-gaz",
        title: "Tebigy gaz tölegi",
        subtitle: "Gaz tölegi",
        icon: "flame-outline",
        iconFamily: "Ionicons",
        color: "#f97316",
        status: "coming_soon",
      },
      {
        id: "elektrik",
        title: "Elektrik energiýasy",
        subtitle: "Tok tölegi",
        icon: "flash-outline",
        iconFamily: "Ionicons",
        color: "#eab308",
        status: "coming_soon",
      },
      {
        id: "kwartplata",
        title: "Jaý-jemagat hyzmat",
        subtitle: "Kwartplata",
        icon: "business-outline",
        iconFamily: "Ionicons",
        color: "#6366f1",
        status: "coming_soon",
      },
      {
        id: "zibil",
        title: "Zibil çykarmak",
        subtitle: "Sanitariýa tölegi",
        icon: "trash-outline",
        iconFamily: "Ionicons",
        color: "#16a34a",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "aragatnasyk",
    title: "Aragatnaşyk we Internet",
    icon: "wifi-outline",
    iconFamily: "Ionicons",
    color: "#0d9488",
    gradientStart: "#0d9488",
    gradientEnd: "#14b8a6",
    enabled: true,
    services: [
      {
        id: "tmcell",
        title: "TMCell",
        subtitle: "Ýaýlym we Internet",
        icon: "phone-portrait-outline",
        iconFamily: "Ionicons",
        color: "#0d9488",
        status: "active",
        route: "/tmcell",
      },
      {
        id: "astu-internet",
        title: "AŞTU",
        subtitle: "Internet & Telefon",
        icon: "globe-outline",
        iconFamily: "Ionicons",
        color: "#0891b2",
        status: "coming_soon",
      },
      {
        id: "telekom-internet",
        title: "Türkmentelekom",
        subtitle: "Internet & Telefon",
        icon: "server-outline",
        iconFamily: "Ionicons",
        color: "#7c3aed",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "telayaylym",
    title: "Teleýaýlym we Mediýa",
    icon: "tv-outline",
    iconFamily: "Ionicons",
    color: "#db2777",
    gradientStart: "#be185d",
    gradientEnd: "#db2777",
    enabled: true,
    services: [
      {
        id: "alem-tv",
        title: "Älem TV",
        subtitle: "Sanly teleýaýlym",
        icon: "tv-outline",
        iconFamily: "Ionicons",
        color: "#db2777",
        status: "coming_soon",
      },
      {
        id: "astu-iptv",
        title: "AŞTU IPTV",
        subtitle: "Telekom IPTV",
        icon: "play-circle-outline",
        iconFamily: "Ionicons",
        color: "#0891b2",
        status: "coming_soon",
      },
      {
        id: "kabel-tv",
        title: "Kabel TV",
        subtitle: "Kabel teleýaýlym",
        icon: "git-branch-outline",
        iconFamily: "Ionicons",
        color: "#6366f1",
        status: "coming_soon",
      },
      {
        id: "belet-film",
        title: "Belet Film",
        subtitle: "Wideo we Kino",
        icon: "film-outline",
        iconFamily: "Ionicons",
        color: "#7c3aed",
        status: "coming_soon",
      },
      {
        id: "tmcell-kino",
        title: "TMCell Kino",
        subtitle: "Kino we Saz",
        icon: "musical-notes-outline",
        iconFamily: "Ionicons",
        color: "#f59e0b",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "dowlet-toleg",
    title: "Döwlet tölegleri",
    icon: "shield-checkmark-outline",
    iconFamily: "Ionicons",
    color: "#dc2626",
    gradientStart: "#b91c1c",
    gradientEnd: "#dc2626",
    enabled: true,
    services: [
      {
        id: "dowlet-sowd",
        title: "Döwlet söwda gözegçiligi",
        subtitle: "Döwlet gullugy",
        icon: "checkmark-circle-outline",
        iconFamily: "Ionicons",
        color: "#dc2626",
        status: "coming_soon",
      },
      {
        id: "pasport",
        title: "Pasport tölegleri",
        subtitle: "Resminamalary",
        icon: "card-outline",
        iconFamily: "Ionicons",
        color: "#2563eb",
        status: "coming_soon",
      },
      {
        id: "ruhnama",
        title: "Ruhnama (ZAGS)",
        subtitle: "ZAGS tölegleri",
        icon: "heart-outline",
        iconFamily: "Ionicons",
        color: "#e11d48",
        status: "coming_soon",
      },
      {
        id: "notarius",
        title: "Notarius hyzmatlary",
        subtitle: "Notarial tölegler",
        icon: "document-text-outline",
        iconFamily: "Ionicons",
        color: "#7c3aed",
        status: "coming_soon",
      },
      {
        id: "kazyyet",
        title: "Kazyýet tölegleri",
        subtitle: "Sud tölegleri",
        icon: "scale-outline",
        iconFamily: "Ionicons",
        color: "#d97706",
        status: "coming_soon",
      },
      {
        id: "salgytlar",
        title: "Salgytlar",
        subtitle: "Soliq to'lovlari",
        icon: "receipt-outline",
        iconFamily: "Ionicons",
        color: "#16a34a",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "bilim",
    title: "Bilim we Terbiýe",
    icon: "school-outline",
    iconFamily: "Ionicons",
    color: "#7c3aed",
    gradientStart: "#6d28d9",
    gradientEnd: "#7c3aed",
    enabled: true,
    services: [
      {
        id: "chagalar-bagy",
        title: "Çagalar bagy",
        subtitle: "Bog'cha tölegi",
        icon: "happy-outline",
        iconFamily: "Ionicons",
        color: "#f59e0b",
        status: "coming_soon",
      },
      {
        id: "mekdep",
        title: "Mekdep tölegleri",
        subtitle: "Mekdep tölegi",
        icon: "school-outline",
        iconFamily: "Ionicons",
        color: "#7c3aed",
        status: "coming_soon",
      },
      {
        id: "otm",
        title: "Ýokary okuw jaýy",
        subtitle: "OTM şertnamasy",
        icon: "library-outline",
        iconFamily: "Ionicons",
        color: "#0d9488",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "saglyk",
    title: "Saglygy goraýyş we Ätiýaç",
    icon: "medkit-outline",
    iconFamily: "Ionicons",
    color: "#059669",
    gradientStart: "#047857",
    gradientEnd: "#059669",
    enabled: true,
    services: [
      {
        id: "poliklinika",
        title: "Saglyk öýleri",
        subtitle: "Poliklinikalar",
        icon: "medkit-outline",
        iconFamily: "Ionicons",
        color: "#059669",
        status: "coming_soon",
      },
      {
        id: "sugurta",
        title: "Ätiýaçlandyryş",
        subtitle: "Meýletin sug'urta",
        icon: "shield-outline",
        iconFamily: "Ionicons",
        color: "#0ea5e9",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "maliye",
    title: "Maliýe we Karzlar",
    icon: "wallet-outline",
    iconFamily: "Ionicons",
    color: "#f59e0b",
    gradientStart: "#d97706",
    gradientEnd: "#f59e0b",
    enabled: true,
    services: [
      {
        id: "kredit",
        title: "Karz tölegleri",
        subtitle: "Kredit tölegi",
        icon: "cash-outline",
        iconFamily: "Ionicons",
        color: "#f59e0b",
        status: "coming_soon",
      },
      {
        id: "p2p",
        title: "Kartdan karta",
        subtitle: "P2P geçirim",
        icon: "swap-horizontal-outline",
        iconFamily: "Ionicons",
        color: "#6366f1",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "hayr-sogap",
    title: "Haýyr-sogap",
    icon: "heart-outline",
    iconFamily: "Ionicons",
    color: "#e11d48",
    gradientStart: "#be123c",
    gradientEnd: "#e11d48",
    enabled: true,
    services: [
      {
        id: "fondlar",
        title: "Fondlar we Kömek",
        subtitle: "Haýyr-sogap fondlar",
        icon: "heart-outline",
        iconFamily: "Ionicons",
        color: "#e11d48",
        status: "coming_soon",
      },
      {
        id: "metjit",
        title: "Metjitler üçin",
        subtitle: "Masjidlar uchun",
        icon: "star-outline",
        iconFamily: "Ionicons",
        color: "#f59e0b",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "oyunlar",
    title: "Oýunlar we Güýmenje",
    icon: "game-controller-outline",
    iconFamily: "Ionicons",
    color: "#6366f1",
    gradientStart: "#4f46e5",
    gradientEnd: "#6366f1",
    enabled: true,
    services: [
      {
        id: "online-oyun",
        title: "Onlaýn oýunlar",
        subtitle: "Kibersport tölegleri",
        icon: "game-controller-outline",
        iconFamily: "Ionicons",
        color: "#6366f1",
        status: "coming_soon",
      },
      {
        id: "tmcell-esports",
        title: "TMCell e-sports",
        subtitle: "E-sport ýaryşlary",
        icon: "trophy-outline",
        iconFamily: "Ionicons",
        color: "#f59e0b",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "awtoduralga",
    title: "Awtoduralga we Ýollar",
    icon: "car-outline",
    iconFamily: "Ionicons",
    color: "#0891b2",
    gradientStart: "#0e7490",
    gradientEnd: "#0891b2",
    enabled: true,
    services: [
      {
        id: "parkovka",
        title: "Pulluk awtoduralgalar",
        subtitle: "Parkovka tölegi",
        icon: "car-outline",
        iconFamily: "Ionicons",
        color: "#0891b2",
        status: "coming_soon",
      },
      {
        id: "awtoban",
        title: "Tiz ýörelişli ýollar",
        subtitle: "Awtoban tölegi",
        icon: "navigate-outline",
        iconFamily: "Ionicons",
        color: "#0d9488",
        status: "coming_soon",
      },
    ],
  },
];
