export type ServiceStatus = "active" | "coming_soon" | "disabled";

export interface TransportService {
  id: string;
  title: string;
  subtitle: string;
  icon: string;
  iconFamily: "Ionicons" | "MaterialCommunityIcons" | "Feather";
  color: string;
  status: ServiceStatus;
  route?: string;
}

export interface TransportCategory {
  id: string;
  title: string;
  icon: string;
  iconFamily: "Ionicons" | "MaterialCommunityIcons" | "Feather";
  color: string;
  gradientStart: string;
  gradientEnd: string;
  enabled: boolean;
  services: TransportService[];
}

export const TRANSPORT_CATEGORIES: TransportCategory[] = [
  {
    id: "dowlet-ulaglary",
    title: "Döwlet ulaglary",
    icon: "business-outline",
    iconFamily: "Ionicons",
    color: "#0d9488",
    gradientStart: "#0d9488",
    gradientEnd: "#14b8a6",
    enabled: true,
    services: [
      {
        id: "howayollary",
        title: "Howaýollary",
        subtitle: "Aviabiletlar",
        icon: "airplane-outline",
        iconFamily: "Ionicons",
        color: "#0ea5e9",
        status: "active",
        route: "/howa",
      },
      {
        id: "demiryollary",
        title: "Demirýollary",
        subtitle: "Poyezd biletleri",
        icon: "train-outline",
        iconFamily: "Ionicons",
        color: "#0d9488",
        status: "active",
        route: "/(demiryol)",
      },
      {
        id: "saherara-awtobus",
        title: "Şäherara awtobuslar",
        subtitle: "Welaýatara",
        icon: "bus-outline",
        iconFamily: "Ionicons",
        color: "#7c3aed",
        status: "coming_soon",
      },
      {
        id: "saher-awtobus",
        title: "Şäher içi awtobuslar",
        subtitle: "Ýol kart tölegleri",
        icon: "car-outline",
        iconFamily: "Ionicons",
        color: "#059669",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "hususy-gatnawlar",
    title: "Hususy we Welaýatara",
    icon: "car-sport-outline",
    iconFamily: "Ionicons",
    color: "#f59e0b",
    gradientStart: "#f59e0b",
    gradientEnd: "#f97316",
    enabled: true,
    services: [
      {
        id: "welayatara-taksi",
        title: "Welaýatara taksiler",
        subtitle: "Pyatak / BlaBlaCar",
        icon: "car-outline",
        iconFamily: "Ionicons",
        color: "#f59e0b",
        status: "coming_soon",
      },
      {
        id: "saher-taksi",
        title: "Şäher içi taksi",
        subtitle: "Çalt we arzan",
        icon: "navigate-outline",
        iconFamily: "Ionicons",
        color: "#f97316",
        status: "coming_soon",
      },
      {
        id: "arenda-masyn",
        title: "Arenda maşynlar",
        subtitle: "Günlük kärendä",
        icon: "key-outline",
        iconFamily: "Ionicons",
        color: "#8b5cf6",
        status: "coming_soon",
      },
      {
        id: "ewakuator",
        title: "Ewakuator",
        subtitle: "Bejeriş ýerine",
        icon: "build-outline",
        iconFamily: "Ionicons",
        color: "#ef4444",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "logistika",
    title: "Logistika we Ýük daşama",
    icon: "cube-outline",
    iconFamily: "Ionicons",
    color: "#6366f1",
    gradientStart: "#6366f1",
    gradientEnd: "#8b5cf6",
    enabled: true,
    services: [
      {
        id: "yuk-taksi",
        title: "Ýük taksisi",
        subtitle: "Şäher içinde",
        icon: "truck-outline",
        iconFamily: "Ionicons",
        color: "#6366f1",
        status: "coming_soon",
      },
      {
        id: "welayatara-yukdas",
        title: "Welaýatara ýük",
        subtitle: "Kamaz / Fura",
        icon: "cube-outline",
        iconFamily: "Ionicons",
        color: "#8b5cf6",
        status: "coming_soon",
      },
      {
        id: "kuryer",
        title: "Tiz poçta / Kuryer",
        subtitle: "Çalt eltmek",
        icon: "rocket-outline",
        iconFamily: "Ionicons",
        color: "#ec4899",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "dynch-syyyahat",
    title: "Dynç alyş we Syýahat",
    icon: "partly-sunny-outline",
    iconFamily: "Ionicons",
    color: "#06b6d4",
    gradientStart: "#06b6d4",
    gradientEnd: "#0ea5e9",
    enabled: true,
    services: [
      {
        id: "awaza",
        title: "Awaza gatnawlary",
        subtitle: "Milli syýahatçylyk",
        icon: "water-outline",
        iconFamily: "Ionicons",
        color: "#06b6d4",
        status: "coming_soon",
      },
      {
        id: "sanatoriya",
        title: "Sanatoriýa transporty",
        subtitle: "Archman, Ýyly Suw",
        icon: "flower-outline",
        iconFamily: "Ionicons",
        color: "#0ea5e9",
        status: "coming_soon",
      },
      {
        id: "ekskursia",
        title: "Syýahatçylyk ugurlary",
        subtitle: "Ekskursiyalar",
        icon: "map-outline",
        iconFamily: "Ionicons",
        color: "#10b981",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "pyygg-sanly",
    title: "PÝGG we Sanly hyzmatlar",
    icon: "shield-checkmark-outline",
    iconFamily: "Ionicons",
    color: "#dc2626",
    gradientStart: "#dc2626",
    gradientEnd: "#ef4444",
    enabled: true,
    services: [
      {
        id: "jerimeler",
        title: "PÝGG jerimeler",
        subtitle: "Jarimalarni to'lash",
        icon: "warning-outline",
        iconFamily: "Ionicons",
        color: "#dc2626",
        status: "coming_soon",
      },
      {
        id: "tehosmotr",
        title: "Tehnik gözegçilik",
        subtitle: "Tehosmotr",
        icon: "construct-outline",
        iconFamily: "Ionicons",
        color: "#d97706",
        status: "coming_soon",
      },
      {
        id: "sugurta",
        title: "Ulag ätiýaçlandyryş",
        subtitle: "Sug'urta",
        icon: "document-text-outline",
        iconFamily: "Ionicons",
        color: "#7c3aed",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "yol-komegi",
    title: "Ýol kömegi",
    icon: "help-buoy-outline",
    iconFamily: "Ionicons",
    color: "#ea580c",
    gradientStart: "#ea580c",
    gradientEnd: "#f97316",
    enabled: true,
    services: [
      {
        id: "yangyc",
        title: "Ýangyç eltmek",
        subtitle: "Yoqilg'i kömegi",
        icon: "flame-outline",
        iconFamily: "Ionicons",
        color: "#ea580c",
        status: "coming_soon",
      },
      {
        id: "shinamontaj",
        title: "Göçme şinamontaž",
        subtitle: "Teker çalyşmak",
        icon: "refresh-circle-outline",
        iconFamily: "Ionicons",
        color: "#f59e0b",
        status: "coming_soon",
      },
      {
        id: "akkumulator",
        title: "Akkumulyator",
        subtitle: "Prikurka kömegi",
        icon: "battery-charging-outline",
        iconFamily: "Ionicons",
        color: "#16a34a",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "yorite-gatnawlar",
    title: "Ýörite gatnawlar",
    icon: "star-outline",
    iconFamily: "Ionicons",
    color: "#db2777",
    gradientStart: "#db2777",
    gradientEnd: "#ec4899",
    enabled: true,
    services: [
      {
        id: "zenanlar",
        title: "Zenanlar üçin",
        subtitle: "Faqat ayollar",
        icon: "heart-outline",
        iconFamily: "Ionicons",
        color: "#db2777",
        status: "coming_soon",
      },
      {
        id: "mekdep-awtobus",
        title: "Mekdep awtobusy",
        subtitle: "Okuwçylar üçin",
        icon: "school-outline",
        iconFamily: "Ionicons",
        color: "#f59e0b",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "mikromobillik",
    title: "Mikromobillik",
    icon: "flash-outline",
    iconFamily: "Ionicons",
    color: "#16a34a",
    gradientStart: "#16a34a",
    gradientEnd: "#22c55e",
    enabled: true,
    services: [
      {
        id: "samokat",
        title: "Tokly samokatlar",
        subtitle: "Elektrikli samokat",
        icon: "flash-outline",
        iconFamily: "Ionicons",
        color: "#16a34a",
        status: "coming_soon",
      },
      {
        id: "welosiped",
        title: "Welosiped kärendesi",
        subtitle: "Elektrikli welosiped",
        icon: "bicycle-outline",
        iconFamily: "Ionicons",
        color: "#22c55e",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "bilim-tayyarlyk",
    title: "Bilim we Sanly taýýarlyk",
    icon: "school-outline",
    iconFamily: "Ionicons",
    color: "#7c3aed",
    gradientStart: "#7c3aed",
    gradientEnd: "#8b5cf6",
    enabled: true,
    services: [
      {
        id: "awto-mekdep",
        title: "Awto-mekdepler",
        subtitle: "Sürüjilik kurslary",
        icon: "car-outline",
        iconFamily: "Ionicons",
        color: "#7c3aed",
        status: "coming_soon",
      },
      {
        id: "pyygg-synag",
        title: "PÝGG synaglary",
        subtitle: "Onlaýn testlar",
        icon: "clipboard-outline",
        iconFamily: "Ionicons",
        color: "#6366f1",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "ulag-bazary",
    title: "Ulag bazary",
    icon: "storefront-outline",
    iconFamily: "Ionicons",
    color: "#0891b2",
    gradientStart: "#0891b2",
    gradientEnd: "#06b6d4",
    enabled: true,
    services: [
      {
        id: "ulag-bildirish",
        title: "Ulag bildirişleri",
        subtitle: "Avtobozor e'lonlari",
        icon: "car-sport-outline",
        iconFamily: "Ionicons",
        color: "#0891b2",
        status: "coming_soon",
      },
      {
        id: "plaka-bazary",
        title: "Plaka bazary",
        subtitle: "Raqamlar bazari",
        icon: "grid-outline",
        iconFamily: "Ionicons",
        color: "#06b6d4",
        status: "coming_soon",
      },
    ],
  },
];
